import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers";
import { RouteGuard } from "./routeguard";
import { AnimatedBackground } from "./AnimatedBackground";
import { UserProvider } from "@/Hooks/useData";
import { Navbarviews } from "@/Modules/Navbar/ui/Navbar-views";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 relative overflow-hidden`}
      >
        <Providers>
          <RouteGuard>
          <UserProvider>
            <AnimatedBackground />
            <Navbarviews />
            <div className="relative z-10">
              {children}
            </div>
            </UserProvider>
          </RouteGuard>
        </Providers>
      </body>
    </html>
  );
}